name: Recordatorio Diario Nexion

on:
  schedule:
    # 08:00 AM CDMX es 14:00 UTC
    # 12:00 PM CDMX es 18:00 UTC
    # 03:00 PM CDMX es 21:00 UTC
    - cron: '0 14,18,21 * * *'
  workflow_dispatch: # Esto es para que puedas probarlo picando un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install pandas requests

      - name: Ejecutar script
        run: python bot_recordatorio.py
